core/urls.py
from django.urls import path,include
from . import views
app_name = 'core'
urlpatterns = [ 
    path('', views.HomepageView.as_view(), name="home"),
    path('product-details/<slug>', views.product_details, name="product_details"),
    path("register", views.UserRegistration, name="registration"),
    path("login", views.UserLogin, name="login"),
    path("logout", views.UserLogout, name="logout"),
    path("add-to-card/<int:id>", views.AddToCard, name="addtocard"),
    path("checkout/<int:id>", views.checkout, name="checkout"),
    path("remove_from_card/<int:id>",views.remove_from_card, name="remove_from_card"),
    path("card_update",views.card_update, name="card_update"),
    path("serch",views.product_search, name="serch"),
]

ecom/urls.py
from django.conf import settings
import debug_toolbar
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path("", include('core.urls', namespace="core")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/frontend/checkout.html

{% extends 'base.html' %}
{% load static %}
{% load extra_tags %}

{% block content %}
	 
	<!-- checkout page -->
	<div class="privacy py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<!-- tittle heading -->
			<h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
				<span>C</span>heckout
			</h3>
			<!-- //tittle heading -->
			<div class="checkout-right">
				<h4 class="mb-sm-4 mb-3">Your shopping cart contains:
					<span>{{total_number}} Products</span> and cost: ${{complete_price|floatformat:2}}
				</h4> 
				{% if messages %} 
				{% for message in messages %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert">
					{{message}}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
				  </div>
				{% endfor %} 
			 {% endif %} 
				<div class="table-responsive">
					<table class="timetable_sub">
						<thead>
							<tr>
								<th>SL No.</th>
								<th>Product</th>
								<th>Product Name</th>
								<th>Quality</th>
								<th>Product price</th> 
								<th>Total Price</th>
								<th>Remove</th>
							</tr>
						</thead>
						<tbody>
							
							{% if order_items %}
								<form action="{% url 'core:card_update' %}" method="POST"> {% csrf_token %}
								{% for item in order_items %}
								<tr class="rem1">
									<td class="invert">{{forloop.counter}}</td>
									<td class="invert-image">
										<a href="{% url 'core:product_details' item.product.slug %}">
											<img src="{{item.product.product_thumbnail.url}}" alt=" " class="img-responsive">
										</a>
									</td>
									<td class="invert">{{item.product.name}}</td>
									<td class="invert">
										<div class="quantity">
											<div class="quantity-select">
												<div onclick="myFunction({{forloop.counter}})" class="entry value-minus">&nbsp;</div>
												<div class="entry value">
													<input type="number" id="quantity_{{forloop.counter}}" class="form-control" name="amount_{{forloop.counter}}" value="{{item.quantity}}">
												</div>
												<div onclick="myFunctionAdd({{forloop.counter}})" class="entry value-plus active">&nbsp;</div>
											</div>
										</div>
									</td>
									<td class="invert">{{item.product.main_price|floatformat:2}}</td>
									<td class="invert">{{item.card_price|floatformat:2}}</td>
									<td class="invert">
										<div class="rem">
											<a href="{% url 'core:remove_from_card' item.product.id %}"><div class="close1"> </div></a>
										</div>
									</td>
								</tr>
								{% endfor %}
								<tr> 
									<td><input class="btn btn-danger" type="submit" value="Update Card"></td>
								</tr>
								
							</form>
							{% endif %}
								 


						</tbody>
					</table>
				</div>
			</div>
			<div class="checkout-left">
				<div class="address_form_agile mt-sm-5 mt-4">
					<h4 class="mb-sm-4 mb-3">Add a new Details</h4>
					<form action="payment.html" method="post" class="creditly-card-form agileinfo_form">
						<div class="creditly-wrapper wthree, w3_agileits_wrapper">
							<div class="information-wrapper">
								<div class="first-row">
									<div class="controls form-group">
										<input class="billing-address-name form-control" type="text" name="name" placeholder="Full Name" required="">
									</div>
									<div class="w3_agileits_card_number_grids">
										<div class="w3_agileits_card_number_grid_left form-group">
											<div class="controls">
												<input type="text" class="form-control" placeholder="Mobile Number" name="number" required="">
											</div>
										</div>
										<div class="w3_agileits_card_number_grid_right form-group">
											<div class="controls">
												<input type="text" class="form-control" placeholder="Landmark" name="landmark" required="">
											</div>
										</div>
									</div>
									<div class="controls form-group">
										<input type="text" class="form-control" placeholder="Town/City" name="city" required="">
									</div>
									<div class="controls form-group">
										<select class="option-w3ls">
											<option>Select Address type</option>
											<option>Office</option>
											<option>Home</option>
											<option>Commercial</option>

										</select>
									</div>
								</div>
								<button class="submit check_out btn">Delivery to this Address</button>
							</div>
						</div>
					</form>
					<div class="checkout-right-basket">
						<a href="payment.html">Make a Payment
							<span class="far fa-hand-point-right"></span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //checkout page -->



	{% endblock content %}
	
	{% block script %}
		<script>
			function myFunction(e) {  
				id = "quantity_"+e.toString() 
				x = document.getElementById(id).value; 
				x = x-1;
				document.getElementById(id).setAttribute('value',x);
 
			}

			function myFunctionAdd(e) {  
				id = "quantity_"+e.toString() 
				x = document.getElementById(id).value;  
				x++;
				document.getElementById(id).setAttribute('value',x);
 
			}



		</script>
	{% endblock script %}
		

templates/frontend/product_details.html
{% extends 'base.html' %}

{% block title %}
	Wealshop | {{product.name}}
{% endblock title %}
	
{% block content %}

{% load static %}
{% load crispy_forms_tags %}

	<div class="banner-bootom-w3-agileits py-5">
		<div class="container py-xl-4 py-lg-2"> 
			<div class="row">
				<div class="col-lg-5 col-md-8 single-right-left ">
					<div class="grid images_3_of_2">
						<div class="flexslider">
							<ul class="slides">
								<li data-thumb="/media/{{product.product_thumbnail}}">
									<div class="thumb-image">
										<img src="/media/{{product.product_thumbnail}}" data-imagezoom="true" class="img-fluid" alt=""> </div>
								</li>
								{% for item in product.product_galary_image.all %} 
								<li data-thumb="/media/{{item.images}}">
									<div class="thumb-image">
										<img src="/media/{{item.images}}" data-imagezoom="true" class="img-fluid" alt=""> </div>
								</li>
								{% endfor %}

							</ul>
							<div class="clearfix"></div>
						</div>
					</div>
				</div>

				<div class="col-lg-7 single-right-left simpleCart_shelfItem">
					<h3 class="mb-3">{{product.title}}</h3>
					
					{% if avg_review == 0 %}
						<p>Product Review: <strong style="color: red;">
							No Review</strong> yet</p> 
					{% else %}
					<p>Product Review: <strong style="color: red;">
						{{avg_review|floatformat:1}}
					</strong> based on {{total_user}} customers</p>
					{% endif %}
					
						

					<p class="mb-3">
						<span class="item_price">{{product.main_price|floatformat:2}}</span>
							<del>{{product.regular_price|floatformat:2}}</del>
							
							{% if product.offer_price and product.discount_price %}
								<span class="ml-2 badge badge-danger">Save {{product.takaoff}} + {{product.offer_price}}%</span>
							{% elif product.discount_price %}
								<span class="ml-2 badge badge-danger">Save {{product.takaoff}}</span>
							{% elif product.offer_price %}
								<span class="ml-2 badge badge-danger">Save{{product.offer_price}}%</span>
							{% endif %}
						
						{% if product. %}
						<label class="d-block">Free delivery</label>
						{% endif %}
							
					</p>
					<div class="single-infoagile">
						{{product.top_optional_text}}
					</div>
					<br>
					<div class="product-single-w3l pt-3"> 
							{{product.top_optional_text}} 
					</div>
					<br>
					<div class="occasion-cart">
						<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out"> 
							<a href="{% url 'core:addtocard' product.id %}" class="btn button btn-primary btn-lg d-block">Add to cart</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
<hr> 

<section class="product_review_area">
	<div class="container">
		<div class="row">
			<div class="col-6">
				<h2 class="card-title">Comments</h2>
				<form action="" method="POST">
					{% csrf_token %}
					<p class="card-text">Your Review out of Five</p>
					{{form.review_number|as_crispy_field}}
					<p class="card-text">Your Comment about the product</p>
					{{form.review_content|as_crispy_field}}
					<input type="submit" class="btn btn-success" value="Post Your Review">
				</form>
			</div>
		</div>
	</div>
</section>
<hr>
<section class="product_reveiw">
	<div class="container">
		<div class="row">
			<div class="col">
				{% for item in review %}
					<div class="single_reivew card card-body">
						<h2 class="card-title">{{item.review_user.name}} -- {{item.review_number}}</h2>
						<p class="card-text">{{item.review_date}}</p>
						<p class="card-text">{{item.review_content}}</p> 
					</div>
				{% endfor %}
			</div>
		</div>
	</div>

		
</section>
<hr>
	
	{% endblock content %}
	
	{% block script %} 

	<script src="{% static '/js/imagezoom.js' %}"></script>
		<!-- flexslider -->
	<link rel="stylesheet" href="{% static '/css/flexslider.css' %}" type="text/css" media="screen" />

	<script src="{% static '/js/jquery.flexslider.js' %}"></script>
	<script>
		// Can also be used with $(document).ready()
		$(window).load(function () {
			$('.flexslider').flexslider({
				animation: "slide",
				controlNav: "thumbnails"
			});
		});
	</script>
	<!-- //FlexSlider-->
	{% endblock script %}
		

templates/frontend/product_search.html
{% extends 'base.html' %}
{% load extra_tags %}
{% block content %}
	<!-- top Products -->
	<div class="ads-grid py-sm-5 py-4">
		<div class="container py-xl-4 py-lg-2">
			<!-- tittle heading -->
			<h3 class="tittle-w3l text-center mb-lg-5 mb-sm-4 mb-3">
				<span>M</span>obiles
				<span>&</span>
				<span>C</span>omputers</h3>
			<!-- //tittle heading -->
			<div class="row">
				<!-- product left -->
				<div class="agileinfo-ads-display col-lg-9">
					<div class="wrapper">
						<!-- first section -->
						<div class="product-sec1 px-sm-4 px-3 py-sm-5  py-3 mb-4">
							<div class="row">
                                {% if products %}  
								{% for item in products %} 
									<div class="col-md-4 product-men mt-5">
										<div class="men-pro-item simpleCart_shelfItem">
											<div class="men-thumb-item text-center">
												<img src="{{item.product_thumbnail.url}}" alt="">
												<div class="men-cart-pro">
													<div class="inner-men-cart-pro">
														<a href="{% url 'core:product_details' item.slug %}" class="link-product-add-cart">Quick View</a>
													</div>
												</div> 
												{% if item.new_arival %}
													<span class="product-new-top">New</span>
												{% endif %} 
											</div>
											<div class="item-info-product text-center border-top mt-4">
												<h4 class="pt-1">
													<a href="single.html">{{item.name}}</a>
												</h4>
												<div class="info-product-price my-2">
													<span class="item_price">{{item.main_price|floatformat:2}}</span>
													<del>{{item.regular_price|floatformat:2}}</del>
													
													{% if item.offer_price and item.discount_price %}
														<span class="ml-2 badge badge-danger">Save {{item.takaoff|floatformat:0}} + {{item.offer_price|floatformat:0}}%</span>
													{% elif item.discount_price %}
														<span class="ml-2 badge badge-danger">Save {{item.takaoff|floatformat:0}}</span>
													{% elif item.offer_price %}
														<span class="ml-2 badge badge-danger">Save{{item.offer_price|floatformat:0}}%</span>
													{% endif %}

														
													
												</div>
												
												{% if item.id|check_card:request.session.id == 1 %}
												<del>
												<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out"> 
													<a style="pointer-events: none; cursor: default;" href="{% url 'core:addtocard' item.id %}" class="btn button btn-primary d-block">Already in Cart</a>
												</div>
											</del>
												{% endif %}
												{% if item.id|check_card:request.session.id == 2 %}
												<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out"> 
													<a href="{% url 'core:addtocard' item.id %}?next={{request.path}}" class="btn button btn-primary d-block">Add to cart</a>
												</div>
												
												{% endif %}
												
 

											</div>
										</div>
									</div>
								{% endfor %}
							{% else %}
							 <p class="card-text">Sorry, There is no products in this Category</p>
							{% endif %}
							</div>
						</div>


					</div>
				</div>
				<!-- //product left -->
				<!-- product right -->
                {% include 'base/sidebar.html' %}
			</div>
		</div>
	</div>
	<!-- //top products -->
 
{% endblock content %}
    

templates/frontend/user_registration.html
{% extends 'base.html' %}

{% block content %}
    <section class="registration_page mt-4 mb-4">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <ul class="card list-group list">
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                        <li class="list-group-item">Computer is a wonder of modern</li>
                    </ul>
                </div>
                <div class="col-8"> 
                    {% if messages %} 
                        {% for message in messages%}
                            {% if message.tags == "error" %}
                                <div class="alert alert-danger">
                                    {{message}}
                                </div>
                            {% else %}
                                <div class="alert alert-success">
                                    {{message}}
                                </div>
                            {% endif %} 
                        {% endfor %} 
                    {% endif %}
                    
                    {% if not request.session.user %}
                        <section class="registration_area">
                            <div class="container">
                                <div class="row">
                                    <div class="col">
                                        <div class="form">
                                            <form action="{% url 'core:login' %}" method="post"> {% csrf_token %}
                                                <div class="form-group">
                                                    <label class="col-form-label">User Email</label>
                                                    <input type="email" class="form-control" placeholder=" " name="email" required="">
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-form-label">Password</label>
                                                    <input type="password" class="form-control" placeholder=" " name="password" required="">
                                                </div>
                                                <div class="right-w3l">
                                                    <input type="submit" class="form-control" value="Log in">
                                                </div>
                                                <div class="sub-w3l">
                                                    <div class="custom-control custom-checkbox mr-sm-2">
                                                        <input type="checkbox" class="custom-control-input" id="customControlAutosizing">
                                                        <label class="custom-control-label" for="customControlAutosizing">Remember me?</label>
                                                    </div>
                                                </div>
                                                <p class="text-center dont-do mt-3">Don't have an account?
                                                    <a href="#" data-toggle="modal" data-target="#exampleModal2">
                                                        Register Now</a>
                                                </p>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    {% endif %}
                        
                        
                        
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
    